### ISSUE TITLE
SQL String generation for put and save can fail

### ISSUE THREAD

**Issue by cansik** [cansik/pg4nosql#14]
This is because of the bad conversion from object to string. None object will not be recognised.

**Comment by cansik** [comment]
With this code:

``` python
record = self.relational_table.get(self.first_relational)
record['height'] = None
self.relational_table.save(record)
record = self.relational_table.get(self.first_relational)
self.assertEqual(None, record['height'])
```

This can happen:

```
Error
Traceback (most recent call last):
  File "/Users/cansik/Projects/pg2nosql/test/PostgresNoSQLTableTest.py", line 89, in test_save_relational_with_none
    self.relational_table.save(record)
  File "/Users/cansik/Projects/pg2nosql/pg4nosql/PostgresNoSQLTable.py", line 55, in save
    json.dumps(data), AsIs(relational_data_sql), object_id))
  File "/Library/Python/2.7/site-packages/psycopg2/extras.py", line 223, in execute
    return super(RealDictCursor, self).execute(query, vars)
DataError: invalid input syntax for type real: "None"
LINE 1: ...{"color": "blue", "items": 3}' , age='24', height='None', na...
```
